### ISSUE TITLE
Error trying to execute the add on

### ISSUE THREAD

**Issue by walterpalladino** [g3ntile/parentToNearestBone#1]
Hi,
I tried the add on and when executed I get some errors. 
I attached the image when you can read the error message at the end TypeError: '<' not supported between instances of 'EditBone' and 'EditBone' Related to line 57

        closest = min( [ (math.dist(getGeometryCenter(ob), loc2world(ar, bone.center)), bone) for bone in ar.data.edit_bones ])

called from 161 and previously 198.

I'm using Blender 3.5 on a Mac M1.

Any idea what could cause this?

Thank you in advance.
Walter--

<img width="1440" alt="Screenshot 2023-05-18 at 10 00 52 AM" src="https://github.com/g3ntile/parentToNearestBone/assets/1933925/a7304674-849d-454b-930c-aacb61c2647e">

**Comment by g3ntile** [comment]
You are trying to parent it in Edit mode. 
You should be in OBJECT mode.
Select all the objects you want to parent, then the armature, and make sure the armature is the active object.
Then go to Object–> Parent–>Parent to nearest bone and it should work.
I hope this fixes it.
Thank you for your interest!

**Comment by walterpalladino** [comment]
Hi,
I found the problem.
The different parts had Mirror modifier. The script crash when the part is not directly mirrored on X like two halves of the same piece but like the armes which should be affected by two different bones.
I applied the Mirror modifier and separated those parts and it worked like charm.
Thank you.
Walter--

**Comment by g3ntile** [comment]
Oh! I never stumbled upon that error, thank you for reporting it!
I'll try to fix it or at least catch the error properly and inform it.
Thank you!

**Comment by walterpalladino** [comment]
No problem. I'm not sure if it is possible to force apply the modifiers but even in that case, I don't know if automatically can separate parts.
Regards.
Walter--

**Comment by g3ntile** [comment]
I think I understand. This addon assumes the rigging situation in which you have many different parts, like in a kitbashed model and you want to parent each different object to some bones. You can't have both arms in one object with the center at the origin, because even if you parent the object to a bone manually you can't have each arm parented to a different bone, because it's one object, unless you do weight mapping, but that's another rigging technique, not covered by this addon. Anyway, an elegant error catcher would be a nice feature for that case.
Thanks again!

**Comment by walterpalladino** [comment]
Just in case could be of use for you, I created an add on to apply Mirror and separate Meshes that I can run before yours to avoid problems.
You can check it at: https://github.com/walterpalladino/applyMirrorAndSeparate
Regards.
Walter--

**Comment by g3ntile** [comment]
Great! 
I added a link to your addon in the Readme, and starred it.
Thank you!

**Comment by walterpalladino** [comment]
Thank You!!!
